### PR TITLE
Programmatically access to configuration files in application runtime

### PR DESCRIPTION
**Pull request by av-k**
I faced with task - receive properties from **tiapp.xml** in application runtime. If i trying get configuration files from source path of application - it's doesn't work expected and guaranteed for both platforms (iOS / Android). 

I found the best solution for myself - at the time of the build progress. Copy config files in the resources directory (static files), in that case we always can get access for this files.

Added new flag **tiappenvcopyto**.

### CODE REVIEW

**Comment by Jei** [comment]
Do you need to read properties from the tiapp.xml file that are for the environment you compiled?
Normally, to do that you would write a property directly in the tiapp.xml and use `Ti.App.Properties` to retrieve it, [as described in the Titanium documentation](https://docs.appcelerator.com/platform/latest/#!/api/Titanium.App.Properties).
Is there a specific case where this solution doesn't work for you?

**Comment by av-k** [comment]
Yep, it's make sense for all others values which are different from format:
`<property name></property>`
As example it will be:
```javascript
<ios>
  <plist>
     <dict>
        <key>FacebookAppID</key>
        <string>999999999999999</string>
    </dict>
  </plist>
</ios>
```
And other platform specific variables...

**Comment by Jei** [comment]
Personally, I'd use the same variable both in the `<plist>` part of the tiapp and in a `<property>`, like:

```
<ti:app
  xmlns:ti="http://ti.appcelerator.org">
  <property name="fb.appid">${app.ios.FBAppID}</property>
  <ios>
    <plist>
      <dict>
        <key>FacebookAppID</key>
        <string>${app.ios.FBAppID}</string>
      </dict>
    </plist>
  </ios>
</ti:app>
```

rather than bothering writing the whole config file in a directory, reading it at runtime and parsing the JSON.
There are a few reasons why this looks like a better idea to me:
- Simple convenience. You can leverage the fact that you are already writing that variable in your `tiapp-cfg.json` and just use it twice;
- Security. By writing your config file in the Resources directory, you are giving away all the variables related to your test environments, which is definitely not ok;
- Most of the times, platform specific variables are already exposed by Titanium, in some way or another. As an example, ti.facebook has a `getAppId()` method.

Even if you think it's still convenient to use this feature (maybe during testing), I don't think this is something that should be handled by tiapp-composer, and it could be written in a separate hook.

**Comment by av-k** [comment]
Make sense, thanks for feedback.

**Pull request closed without merging**
